name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
      contents: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello! Welcome to your issue, please make sure your issue is detailed and you send a kind and respectful message.'
        pr-message: 'Hello! Thank you so much for contributing! Please ensure you validated your CLA, please reload the page to view the CLA bot comment and click on the link. Thank you for your contribution!'
